# Generated by Django 4.2.17 on 2024-12-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlogs',
            name='client_name',
            field=models.CharField(max_length=200),
        ),
    ]
