# Generated by Django 4.2.17 on 2024-12-28 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_clientlogs_client_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientlogs',
            old_name='Coments',
            new_name='coments',
        ),
    ]
